package com.chatApp.Server_Socket.model;

@DynamoDBTable(tableName="MessageHistory")
public class DynamoMessage extends Message {
    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    @DynamoDBPartitionKey
    public String getId() {
        return id;
    }

    @DynamoDBAttribute
    public String getUser() {
            return super.getUser();
    }

    @DynamoDBAttribute
    public Instant getTimeStamp() {
            return super.getTimeStamp();
    }

    @DynamoDBAttribute
    public String getComment() {
            return super.getComment();
    }
    
}

